### ISSUE TITLE
Warning peer dependency Vite 3

### ISSUE THREAD

**Issue by Dyskal** [sergeymakinen/vite-plugin-html-minimize#2]
When installing this plugin, npm warns about unsatisfied peer dependency of Vite@^2 when using Vite 3.
The plugin still works fine as of Vite 3.
Can you please update the version in peer dependencies in the package.json file, thanks.

**Comment by sergeymakinen** [comment]
Sure! Just fixed with https://github.com/sergeymakinen/vite-plugin-html-minimize/commit/952cde305e7ce5758c02228ed6cbd0396176ba02.

**Comment by sohaha** [comment]
@sergeymakinen Now that vite has been upgraded to 4.0, `^2.0.0 || ^3.0.0` is no longer available.
